version: 2

models:
  - name: dim_creator_handle_log
    description: "Time-bounded mapping from handle → TikTok ID for point-in-time joins (valid_from/valid_to)."
    columns:
      - name: tiktok_id
        description: "Unique TikTok ID"
        tests: [not_null]
      - name: handle
        description: "Creator's TikTok Username"
        tests: [not_null]
      - name: valid_from
        description: "Start of validity window (inclusive)"
        tests: [not_null]
      - name: valid_to
        description: "End of validity window (exclusive); NULL = current"

  - name: dim_creator_id_map
    description: "Creator ID mapping table linking Echo creator IDs to TikTok IDs.
      Handles are excluded. The `id` field is normalized by removing
      prefixes (`temp_temp_`, `tiktok_`) and truncating anything after
      an underscore to ensure consistent ID values across sources."
    tests:
      - no_multi_tiktok_per_external_id
    columns:
      - name: map_id
        description: "Deterministic surrogate key generated as md5(id_type || '|' || id || '|' || id_source)."
        tests:
          - not_null
          - unique
      - name: tiktok_id
        description: "TikTok creator ID associated with the Echo creator record. May be null if not available in the Echo source."
        tests: []
      - name: id_type
        description: "Type of the external identifier represented in `id`. For this model, always `echo_creator_id`."
        tests:
          - not_null
          - accepted_values:
              values:
                - echo_creator_id
      - name: id
        description: "Normalized Echo creator ID value. Cleaning logic removes the prefixes `temp_temp_` or `tiktok_` and strips any suffix beginning with `_`."
        tests:
          - not_null
      - name: id_source
        description: "Source system or staging model that provided the ID. For this model, always `echo`."
        tests:
          - not_null
          - accepted_values:
              values:
                - echo
