version: 2

models:
  - name: dim_creator_handle_log
    description: "Time-bounded mapping from handle → TikTok ID for point-in-time joins (valid_from/valid_to)."
    columns:
      - name: tiktok_id
        description: "Unique TikTok ID"
        tests: [not_null]
      - name: handle
        description: "Creator's TikTok Username"
        tests: [not_null]
      - name: valid_from
        description: "Start of validity window (inclusive)"
        tests: [not_null]
      - name: valid_to
        description: "End of validity window (exclusive); NULL = current"

  - name: dim_creator_email
    description:
      One row per (tiktok_id, email) representing email addresses observed for TikTok creators
      across multiple raw sources. Rows are aggregated to earliest created_at and latest
      updated_at for each pair; data_source reflects the row with the latest updated_at.
      is_current flags the most recently updated email for a given tiktok_id.
    columns:
      - name: creator_email_id
        description: "Surrogate key: to_varchar(abs(hash(tiktok_id, email))). Deterministic, positive string."
        tests:
          - not_null
          - unique
      - name: tiktok_id
        description: "Unique TikTok account identifier (from raw sources)."
        tests:
          - not_null
      - name: email
        description: "Creator email address (normalized to lowercase and trimmed in staging)."
        tests:
          - not_null
      - name: data_source
        description: "Source table where the latest record for (tiktok_id, email) came from."
        tests:
          - accepted_values:
              values: ['CREATORINFO', 'HYDRATE', 'MARKET']
      - name: created_at
        description: "Earliest observed create_date for the (tiktok_id, email) pair across sources."
      - name: updated_at
        description: "Most recent observed last_update for the (tiktok_id, email) pair across sources."
      - name: is_current
        description: "True if this email is the most recently updated for the given tiktok_id."
        tests:
          - accepted_values:
              values: [true, false]
