version: 2

sources:
- name: RAW
  database: RAW
  schema: S3
  tables:
    - name: CREATORINFO
    - name: CRMCREATOR
    - name: HYDRATE
    - name: MARKET
    - name: SEARCHINFO
    - name: BRAVO_V1
    - name: BRAVO_V2
    - name: ECHO
    - name: ADDRESS_PHONE
    - name: ZIP_LAT_LON