{{ 
    config(
        materialized='view', 
        tags=['staging','tiktok']
    ) 
}}

select
  tiktok_id::varchar                                          as tiktok_id,
  lower(nullif(trim(handle_name), ''))::varchar              as handle_name,
  nullif(trim(display_name), '')::varchar                    as display_name,
  lower(nullif(trim(email_address), ''))::varchar            as email_address,
  nullif(trim(selectionRegion), '')::varchar                 as selectionRegion,
  followerCount::number                                      as followerCount,
  promotedProductNum::number                                 as promotedProductNum,
  brandCollaborationCount::number                            as brandCollaborationCount,
  avgCommissionRate::float                                   as avgCommissionRate,
  avgCommissionRateRange_min::float                          as avgCommissionRateRange_min,
  avgCommissionRateRange_max::float                          as avgCommissionRateRange_max,
  avgEcLiveCommentCount::number                              as avgEcLiveCommentCount,
  avgEcLiveLikeCount::number                                 as avgEcLiveLikeCount,
  avgEcLiveShareCount::number                                as avgEcLiveShareCount,
  avgEcLiveViewCount::number                                 as avgEcLiveViewCount,
  avgEcVideoCommentCount::number                             as avgEcVideoCommentCount,
  avgEcVideoLikeCount::number                                as avgEcVideoLikeCount,
  avgEcVideoPlayCount::number                                as avgEcVideoPlayCount,
  avgEcVideoShareCount::number                               as avgEcVideoShareCount,
  avgGmvPerBuyer_amount::float                               as avgGmvPerBuyer_amount,
  avgGmvPerBuyerRange_min::float                             as avgGmvPerBuyerRange_min,
  avgGmvPerBuyerRange_max::float                             as avgGmvPerBuyerRange_max,
  gmv_amount::float                                          as gmv_amount,
  gmvRange_min::float                                        as gmvRange_min,
  gmvRange_max::float                                        as gmvRange_max,
  gpm_amount::float                                          as gpm_amount,
  gpmRange_min::float                                        as gpmRange_min,
  gpmRange_max::float                                        as gpmRange_max,
  liveGmv_amount::float                                      as liveGmv_amount,
  liveGpm_amount::float                                      as liveGpm_amount,
  liveGpmRange_min::float                                    as liveGpmRange_min,
  liveGpmRange_max::float                                    as liveGpmRange_max,
  videoGmv_amount::float                                     as videoGmv_amount,
  videoGpm_amount::float                                     as videoGpm_amount,
  videoGpmRange_min::float                                   as videoGpmRange_min,
  videoGpmRange_max::float                                   as videoGpmRange_max,
  productOriginalPriceRange_min::float                       as productOriginalPriceRange_min,
  productOriginalPriceRange_max::float                       as productOriginalPriceRange_max,
  unitsSold::number                                          as unitsSold,
  unitsSoldRange_min::number                                 as unitsSoldRange_min,
  unitsSoldRange_max::number                                 as unitsSoldRange_max,
  ecLiveCount::number                                        as ecLiveCount,
  ecVideoCount::number                                       as ecVideoCount,
  ecLiveEngagementRate::float                                as ecLiveEngagementRate,
  categoryId1::number                                        as categoryId1,
  categoryId2::number                                        as categoryId2,
  categoryId3::number                                        as categoryId3,
  categoryGmv1_id::number                                    as categoryGmv1_id,
  categoryGmv1_value::float                                  as categoryGmv1_value,
  categoryGmv2_id::number                                    as categoryGmv2_id,
  categoryGmv2_value::float                                  as categoryGmv2_value,
  categoryGmv3_id::number                                    as categoryGmv3_id,
  categoryGmv3_value::float                                  as categoryGmv3_value,
  categoryGmv4_id::number                                    as categoryGmv4_id,
  categoryGmv4_value::float                                  as categoryGmv4_value,
  nullif(trim(contentGmvDistribution1_type), '')::varchar    as contentGmvDistribution1_type,
  contentGmvDistribution1_value::float                       as contentGmvDistribution1_value,
  nullif(trim(contentGmvDistribution2_type), '')::varchar    as contentGmvDistribution2_type,
  contentGmvDistribution2_value::float                       as contentGmvDistribution2_value,
  nullif(trim(contentGmvDistribution3_type), '')::varchar    as contentGmvDistribution3_type,
  contentGmvDistribution3_value::float                       as contentGmvDistribution3_value,
  topBrand1::number                                          as topBrand1,
  topBrand2::number                                          as topBrand2,
  topBrand3::number                                          as topBrand3,
  topBrand4::number                                          as topBrand4,
  topBrand5::number                                          as topBrand5,
  topBrand6::number                                          as topBrand6,
  topBrand7::number                                          as topBrand7,
  topBrand8::number                                          as topBrand8,
  topBrand9::number                                          as topBrand9,
  topBrand10::number                                         as topBrand10,
  code::number                                               as code,
  create_date::timestamp_ntz                                          as create_date,
  last_update::timestamp_ntz                                          as last_update
from {{ source('RAW','MARKET') }}
