{{ config(materialized='view', tags=['staging','tiktok']) }}

select
  lower(nullif(trim(handle_name), ''))::varchar              as handle_name,
  tiktok_id::varchar                                          as tiktok_id,
  nullif(trim(bio_description), '')::varchar                 as bio_description,
  nullif(trim(bio_link), '')::varchar                        as bio_link,
  nullif(trim(video_urls), '')::varchar                      as video_urls,
  created_at::timestamp_ntz                                  as created_at,
  updated_at::timestamp_ntz                                  as updated_at,
  lower(nullif(trim(email), ''))::varchar                    as email,
  nullif(trim(unique_qualities), '')::varchar                as unique_qualities,
  nullif(trim(video_background), '')::varchar                as video_background,
  nullif(trim(persona_archetype), '')::varchar               as persona_archetype,
  nullif(trim(lifestyle_alignment), '')::varchar             as lifestyle_alignment,
  nullif(trim(video_contents), '')::varchar                  as video_contents,
  nullif(trim(face_visibility), '')::varchar                 as face_visibility,
  nullif(trim(languages), '')::varchar                       as languages,
  nullif(trim(primary_content_categories), '')::varchar      as primary_content_categories,
  nullif(trim(gender_presentation), '')::varchar             as gender_presentation,
  nullif(trim(race_presentation), '')::varchar               as race_presentation,
  nullif(trim(body_type), '')::varchar                       as body_type,
  nullif(trim(economic_status), '')::varchar                 as economic_status,
  nullif(trim(age_presentation), '')::varchar                as age_presentation,
  nullif(trim(overall_tone), '')::varchar                    as overall_tone,
  nullif(trim(video_quality), '')::varchar                   as video_quality,
  nullif(trim(demonstration_style), '')::varchar             as demonstration_style,
  nullif(trim(hashtags), '')::varchar                        as hashtags,
  nullif(trim(energy_level), '')::varchar                    as energy_level,
  nullif(trim(authenticity_level), '')::varchar              as authenticity_level,
  nullif(trim(content_creator_type), '')::varchar            as content_creator_type,
  nullif(trim(detailed_appearance), '')::varchar             as detailed_appearance,
  nullif(trim(personality_indicators), '')::varchar          as personality_indicators,
  nullif(trim(communication_style), '')::varchar             as communication_style,
  nullif(trim(content_format_specifics), '')::varchar        as content_format_specifics,
  nullif(trim(lifestyle_details), '')::varchar               as lifestyle_details,
  nullif(trim(product_interaction_approach), '')::varchar    as product_interaction_approach,
  nullif(trim(niche_specializations), '')::varchar           as niche_specializations,
  nullif(trim(products_promoted), '')::varchar               as products_promoted,
  nullif(trim(creator_open_id), '')::varchar                 as creator_open_id
from {{ source('RAW','BRAVO_V2') }}
